### PR TITLE
fix: removed the `release` flag and handle the inconsistency when releasing invalid structs

### PR DESCRIPTION
**Pull request by cocoa-xu**

### CODE REVIEW

**Review by josevalim — APPROVED** [review]

**Comment by cocoa-xu** [comment]
I'll do one last change!

**Comment by cocoa-xu** [comment]
It's okay now :D

**Comment by Qqwy** [comment]
Looks great! 🥳

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
